require: rubocop-performance

inherit_gem:
  onkcop:
    - "config/rubocop.yml"

AllCops:
  AllowSymlinksInCacheRootDirectory: true
  DisplayCopNames: true
  Exclude:
    - '**/._*'
    - 'vendor/**/*'
  TargetRubyVersion: 2.5

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
