version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@volatile
  heroku:    circleci/heroku@0.0.2

executors:
  default:
    docker:
      - image: circleci/ruby:2.5.3
        environment:
          RACK_ENV: test
    working_directory: ~/app

jobs:
  rspec:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v2-bundle"
      - run: bundle exec rake test

  rubocop:
    executor:
      name: default

    steps:
      - checkout
      - ruby-orbs/bundle-install:
          cache_key_prefix: "v2-bundle"
      - run: bundle exec rubocop

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - rspec
      - rubocop
      - heroku/deploy-via-git:
          context: Heroku
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: master
