version: 2.0

default: &default
  docker:
    - image: circleci/ruby:2.5.1-node
      environment:
        RACK_ENV: test
  working_directory: ~/app

restore_bundle_cache_option: &restore_bundle_cache_option
  keys:
    - v1-bundle-{{ checksum "Gemfile.lock" }}
    - v1-bundle

restore_repo_cache_option: &restore_repo_cache_option
  key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}

jobs:
  checkout_code:
    <<: *default

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  bundle_dependencies:
    <<: *default

    steps:
      - restore_cache:
          <<: *restore_repo_cache_option
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: ./.circleci/setup_bundle.sh
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/app/vendor/bundle

  rspec:
    <<: *default

    steps:
      - restore_cache:
          <<: *restore_repo_cache_option
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: ./.circleci/setup_bundle.sh

      - run: bundle exec rake test

  rubocop:
    <<: *default

    steps:
      - restore_cache:
          <<: *restore_repo_cache_option
      - restore_cache:
          <<: *restore_bundle_cache_option
      - run: ./.circleci/setup_bundle.sh

      - run: bundle exec rubocop

  deploy:
    docker:
      - image: sue445/heroku-cli
    working_directory: /home/circleci/app

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: .circleci/heroku_setup.sh
      - add_ssh_keys:
          fingerprints:
            - "b3:c5:19:97:09:2e:dd:7e:dd:9d:05:c3:8b:2e:9f:54"
      - run: .circleci/heroku_deploy.sh

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - rspec:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
      - deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: master
