version: 2.1

orbs:
  ruby-orbs: sue445/ruby-orbs@volatile

default: &default
  docker:
    - image: circleci/ruby:2.5.3
      environment:
        RACK_ENV: test
  working_directory: ~/app

jobs:
  rspec:
    <<: *default

    steps:
      - checkout
      - ruby-orbs/bundle-install
      - run: bundle exec rake test

  rubocop:
    <<: *default

    steps:
      - checkout
      - ruby-orbs/bundle-install
      - run: bundle exec rubocop

  deploy:
    docker:
      - image: sue445/heroku-cli
    working_directory: /home/circleci/app

    steps:
      - checkout
      - run: .circleci/heroku_setup.sh
      - add_ssh_keys:
          fingerprints:
            - "b3:c5:19:97:09:2e:dd:7e:dd:9d:05:c3:8b:2e:9f:54"
      - run: .circleci/heroku_deploy.sh

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - rspec
      - rubocop
      - deploy:
          context: Heroku
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: master
