name: test

on:
  push:

env:
  CI: "true"
  RUBYOPT: -EUTF-8

jobs:
  test:
    runs-on: ubuntu-latest

    container: ${{ matrix.ruby }}

    strategy:
      fail-fast: false

      matrix:
        ruby:
          - ruby:2.5
          - ruby:2.6
          - ruby:2.7

    steps:
      - uses: actions/checkout@v2

      - name: bundle update
        run: |
          set -xe
          bundle config path vendor/bundle
          bundle update --jobs $(nproc) --retry 3
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - name: Run test
        run: |
          set -xe
          gem install bundler
          bundle exec test
        continue-on-error: ${{ matrix.allow_failures == 'true' }}

      - name: Run lint
        run: |
          set -xe
          bundle exec rubocop
          bundle exec rubydoctest README.md
        continue-on-error: ${{ matrix.allow_failures == 'true' }}
